name: Rust

on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  doc:
    name: Generate doc
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: cargo doc
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all --no-deps

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: target/doc
